project:
  type: website
    
website:
  site-url: https://eiteldo.github.io/
  repo-url: https://github.com/eiteldo/eiteldo.github.io/
  favicon: favicon.png
  title: "Dominik Eitel"
  navbar:
    left:
      - text: "My research"
        href: index.qmd
      - text: "About me"
        href: about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

execute:
  freeze: auto
  
